Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/14.0.865.0 Safari/537.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_7 rv:5.0; ID) AppleWebKit/531.1.1 (KHTML, like Gecko) Version/6.0.0 Safari/531.1.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/6.0; .NET CLR 2.9.22056.4)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/13.0.820.0 Safari/533.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/20.0.863.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/25.0.856.0 Safari/536.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_0 rv:5.0; AZ) AppleWebKit/533.1.0 (KHTML, like Gecko) Version/6.1.7 Safari/533.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1 rv:2.0; GV) AppleWebKit/532.0.1 (KHTML, like Gecko) Version/4.1.1 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/35.0.826.0 Safari/537.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/17.0.846.0 Safari/534.0.2
Mozilla/5.0 (Windows NT 6.2; WOW64; rv:6.3) Gecko/20100101 Firefox/6.3.8
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/33.0.801.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/18.0.820.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/30.0.821.0 Safari/534.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_9 rv:4.0; VI) AppleWebKit/532.2.1 (KHTML, like Gecko) Version/4.1.1 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/29.0.823.0 Safari/537.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.1.2 (KHTML, like Gecko) Chrome/14.0.895.0 Safari/536.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10.4; rv:11.1) Gecko/20100101 Firefox/11.1.7
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/27.0.870.0 Safari/538.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4 rv:5.0; AF) AppleWebKit/534.0.2 (KHTML, like Gecko) Version/5.0.9 Safari/534.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.0; Trident/6.1; .NET CLR 2.0.13839.3)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/22.0.899.0 Safari/534.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1 rv:4.0; AZ) AppleWebKit/532.1.1 (KHTML, like Gecko) Version/4.0.3 Safari/532.1.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.1; .NET CLR 1.6.15250.4)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/33.0.899.0 Safari/532.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.2.1 (KHTML, like Gecko) Chrome/21.0.836.0 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/21.0.834.0 Safari/532.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/25.0.811.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/18.0.856.0 Safari/531.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_6 rv:6.0; AS) AppleWebKit/532.0.1 (KHTML, like Gecko) Version/4.1.5 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/36.0.867.0 Safari/533.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_5) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/14.0.898.0 Safari/535.1.0
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:5.3) Gecko/20100101 Firefox/5.3.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_3) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/20.0.851.0 Safari/534.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/36.0.885.0 Safari/531.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_1 rv:3.0; EU) AppleWebKit/537.0.0 (KHTML, like Gecko) Version/6.0.8 Safari/537.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/26.0.876.0 Safari/533.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/5.0; .NET CLR 3.6.95874.1)
Mozilla/5.0 (Windows NT 6.0; rv:6.0) Gecko/20100101 Firefox/6.0.6
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/14.0.846.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/16.0.804.0 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/36.0.864.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/26.0.882.0 Safari/531.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_2 rv:2.0; GL) AppleWebKit/537.0.1 (KHTML, like Gecko) Version/7.1.4 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/13.0.888.0 Safari/533.1.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.0; Trident/3.0; .NET CLR 2.2.73055.2)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.2.2 (KHTML, like Gecko) Chrome/18.0.872.0 Safari/532.2.2
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_1 rv:4.0; BO) AppleWebKit/538.2.1 (KHTML, like Gecko) Version/7.1.5 Safari/538.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6.7; rv:11.2) Gecko/20100101 Firefox/11.2.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/7.0; .NET CLR 4.6.45416.4)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/37.0.887.0 Safari/534.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/30.0.848.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/34.0.897.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.1.2 (KHTML, like Gecko) Chrome/34.0.853.0 Safari/538.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/28.0.800.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/27.0.891.0 Safari/531.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6.6; rv:13.7) Gecko/20100101 Firefox/13.7.4
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/27.0.823.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/31.0.873.0 Safari/531.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/17.0.801.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/29.0.820.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.0.2 (KHTML, like Gecko) Chrome/20.0.899.0 Safari/536.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/36.0.860.0 Safari/536.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_7) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/22.0.830.0 Safari/534.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4 rv:3.0; UK) AppleWebKit/532.2.2 (KHTML, like Gecko) Version/4.0.6 Safari/532.2.2
Opera/11.75 (Windows NT 5.3; U; BN Presto/2.9.186 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/36.0.879.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/35.0.810.0 Safari/532.2.0
Opera/12.28 (Windows NT 6.3; U; KG Presto/2.9.170 Version/12.00)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/35.0.835.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/20.0.868.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/25.0.882.0 Safari/532.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/6.0; .NET CLR 4.6.74626.0)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/23.0.852.0 Safari/533.2.2
Mozilla/5.0 (Windows NT 6.2; rv:9.7) Gecko/20100101 Firefox/9.7.7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_6) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/32.0.800.0 Safari/533.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.3; Trident/5.1; .NET CLR 2.0.38669.1)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/36.0.809.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/26.0.834.0 Safari/533.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8 rv:5.0; HT) AppleWebKit/532.2.1 (KHTML, like Gecko) Version/4.0.4 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/23.0.885.0 Safari/531.1.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/3.0; .NET CLR 2.6.10619.6)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/28.0.839.0 Safari/534.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.0.2 (KHTML, like Gecko) Chrome/15.0.801.0 Safari/531.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_7 rv:3.0; AB) AppleWebKit/532.2.2 (KHTML, like Gecko) Version/4.1.0 Safari/532.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/13.0.800.0 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/30.0.830.0 Safari/533.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/28.0.810.0 Safari/531.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/31.0.883.0 Safari/533.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.2.0 (KHTML, like Gecko) Chrome/33.0.883.0 Safari/535.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/26.0.854.0 Safari/537.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; .NET CLR 2.2.90546.2)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.1; Trident/3.0; .NET CLR 1.2.38047.7)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/14.0.841.0 Safari/531.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/30.0.866.0 Safari/534.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5 rv:5.0; CO) AppleWebKit/536.2.1 (KHTML, like Gecko) Version/5.1.8 Safari/536.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/24.0.872.0 Safari/535.0.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/7.1; .NET CLR 3.9.50734.6)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/24.0.869.0 Safari/532.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/35.0.830.0 Safari/532.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/6.0; .NET CLR 1.6.62906.6)
Mozilla/5.0 (Windows NT 6.0; Win64; x64; rv:7.6) Gecko/20100101 Firefox/7.6.7
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_9 rv:2.0; OC) AppleWebKit/531.2.2 (KHTML, like Gecko) Version/4.0.1 Safari/531.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_9 rv:5.0; AF) AppleWebKit/538.2.1 (KHTML, like Gecko) Version/7.0.2 Safari/538.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_9) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/32.0.850.0 Safari/538.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/34.0.856.0 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/32.0.850.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/22.0.803.0 Safari/537.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/31.0.888.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/24.0.883.0 Safari/536.2.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4 rv:4.0; KO) AppleWebKit/531.1.2 (KHTML, like Gecko) Version/5.0.6 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/35.0.889.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/21.0.882.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/30.0.871.0 Safari/537.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/21.0.893.0 Safari/531.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8 rv:5.0; TR) AppleWebKit/534.2.1 (KHTML, like Gecko) Version/4.1.9 Safari/534.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/23.0.880.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/20.0.849.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/39.0.815.0 Safari/534.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_3) AppleWebKit/531.0.2 (KHTML, like Gecko) Chrome/36.0.885.0 Safari/531.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/5.1; .NET CLR 3.1.10861.0)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/20.0.852.0 Safari/532.2.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/4.1; .NET CLR 1.1.51111.5)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/31.0.897.0 Safari/536.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_1 rv:2.0; MO) AppleWebKit/533.0.2 (KHTML, like Gecko) Version/6.1.3 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/23.0.829.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/21.0.838.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/15.0.815.0 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/532.2.2 (KHTML, like Gecko) Chrome/25.0.868.0 Safari/532.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/35.0.880.0 Safari/535.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/18.0.832.0 Safari/536.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.8.1; rv:9.1) Gecko/20100101 Firefox/9.1.5
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.2.0 (KHTML, like Gecko) Chrome/29.0.892.0 Safari/537.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_6) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/38.0.843.0 Safari/535.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/28.0.879.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/21.0.887.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.1.2 (KHTML, like Gecko) Chrome/33.0.898.0 Safari/538.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/33.0.863.0 Safari/538.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_8 rv:2.0; BG) AppleWebKit/532.2.1 (KHTML, like Gecko) Version/5.1.3 Safari/532.2.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3 rv:5.0; AR) AppleWebKit/531.0.1 (KHTML, like Gecko) Version/4.0.9 Safari/531.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/33.0.804.0 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/31.0.820.0 Safari/533.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/30.0.856.0 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/26.0.897.0 Safari/538.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.8.0; rv:15.2) Gecko/20100101 Firefox/15.2.8
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/5.1; .NET CLR 2.0.85629.1)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/22.0.884.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/16.0.811.0 Safari/537.2.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/7.0; .NET CLR 1.5.76823.6)
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/7.1; .NET CLR 1.7.60837.7)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/37.0.896.0 Safari/538.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7.4; rv:6.6) Gecko/20100101 Firefox/6.6.3
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_1) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/33.0.888.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/22.0.810.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/23.0.853.0 Safari/536.2.2
Mozilla/5.0 (Windows NT 5.2; rv:10.5) Gecko/20100101 Firefox/10.5.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/38.0.801.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.1 (KHTML, like Gecko) Chrome/26.0.864.0 Safari/536.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_2 rv:6.0; KO) AppleWebKit/534.1.1 (KHTML, like Gecko) Version/5.1.5 Safari/534.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/39.0.844.0 Safari/532.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_0 rv:3.0; SK) AppleWebKit/536.0.2 (KHTML, like Gecko) Version/5.0.0 Safari/536.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/23.0.847.0 Safari/533.1.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.3; Trident/5.0; .NET CLR 1.8.25200.7)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/32.0.850.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/15.0.887.0 Safari/532.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/14.0.865.0 Safari/534.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_6 rv:3.0; MN) AppleWebKit/536.1.1 (KHTML, like Gecko) Version/7.0.10 Safari/536.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7.3; rv:10.1) Gecko/20100101 Firefox/10.1.4
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/22.0.877.0 Safari/532.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9 rv:4.0; BR) AppleWebKit/535.1.2 (KHTML, like Gecko) Version/5.0.0 Safari/535.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.1.2 (KHTML, like Gecko) Chrome/29.0.811.0 Safari/538.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/20.0.887.0 Safari/533.1.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/3.0; .NET CLR 3.6.91935.9)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/30.0.875.0 Safari/531.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.0; Trident/6.1; .NET CLR 3.5.83323.6)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/15.0.814.0 Safari/536.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9.7; rv:5.0) Gecko/20100101 Firefox/5.0.9
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_6 rv:4.0; CU) AppleWebKit/535.1.1 (KHTML, like Gecko) Version/4.0.10 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/37.0.806.0 Safari/535.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_9) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/22.0.880.0 Safari/534.0.0
Mozilla/5.0 (Windows NT 5.1; WOW64; rv:12.1) Gecko/20100101 Firefox/12.1.8
Opera/14.20 (Windows NT 5.2; U; EL Presto/2.9.189 Version/11.00)
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/5.0; .NET CLR 4.9.72688.3)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/34.0.825.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/39.0.854.0 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/21.0.886.0 Safari/535.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_9 rv:4.0; UR) AppleWebKit/536.1.2 (KHTML, like Gecko) Version/5.0.8 Safari/536.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3 rv:5.0; FA) AppleWebKit/532.1.1 (KHTML, like Gecko) Version/6.0.9 Safari/532.1.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.3; Trident/7.0; .NET CLR 4.7.61321.6)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/5.0; .NET CLR 2.6.46559.0)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/34.0.831.0 Safari/533.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_1 rv:2.0; CS) AppleWebKit/538.2.0 (KHTML, like Gecko) Version/4.1.5 Safari/538.2.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/3.0; .NET CLR 4.2.94591.6)
Mozilla/5.0 (Macintosh; PPC Mac OS X 10_8_6 rv:4.0; YI) AppleWebKit/536.2.0 (KHTML, like Gecko) Version/5.0.3 Safari/536.2.0
Mozilla/5.0 (Windows NT 6.2; WOW64; rv:6.8) Gecko/20100101 Firefox/6.8.4
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/27.0.898.0 Safari/531.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_2) AppleWebKit/532.2.1 (KHTML, like Gecko) Chrome/16.0.892.0 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.2.0 (KHTML, like Gecko) Chrome/14.0.870.0 Safari/535.2.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/7.1; .NET CLR 2.6.24726.3)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/22.0.809.0 Safari/534.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/32.0.831.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/39.0.803.0 Safari/533.1.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; .NET CLR 1.1.51467.2)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/14.0.842.0 Safari/534.0.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Trident/6.1; .NET CLR 2.9.36008.9)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8 rv:6.0; NL) AppleWebKit/535.0.0 (KHTML, like Gecko) Version/6.0.4 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/35.0.809.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/13.0.843.0 Safari/538.1.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.1; Trident/6.0; .NET CLR 2.6.58134.9)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/28.0.899.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/25.0.867.0 Safari/533.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/37.0.803.0 Safari/534.2.0
Mozilla/5.0 (Windows NT 5.2; WOW64; rv:12.1) Gecko/20100101 Firefox/12.1.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/3.1; .NET CLR 3.9.44414.9)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/15.0.858.0 Safari/535.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/14.0.803.0 Safari/532.1.2
Opera/12.87 (Windows NT 6.3; U; SQ Presto/2.9.179 Version/12.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_6) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/19.0.807.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/16.0.863.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/20.0.885.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/21.0.819.0 Safari/538.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/5.0; .NET CLR 4.3.61498.9)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.1.2 (KHTML, like Gecko) Chrome/24.0.811.0 Safari/535.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/26.0.845.0 Safari/534.0.1
Opera/9.68 (Windows NT 6.0; U; AS Presto/2.9.160 Version/12.00)
Opera/12.95 (Windows NT 5.0; U; MK Presto/2.9.177 Version/10.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_2 rv:5.0; DE) AppleWebKit/535.1.0 (KHTML, like Gecko) Version/5.1.3 Safari/535.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4 rv:2.0; SO) AppleWebKit/533.0.0 (KHTML, like Gecko) Version/5.0.2 Safari/533.0.0
Opera/10.31 (Windows NT 6.0; U; AR Presto/2.9.183 Version/11.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_4 rv:2.0; HI) AppleWebKit/537.2.1 (KHTML, like Gecko) Version/7.1.6 Safari/537.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/35.0.879.0 Safari/538.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.3; Trident/5.0; .NET CLR 4.8.62848.1)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/5.0; .NET CLR 3.0.65090.2)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/23.0.854.0 Safari/534.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/18.0.880.0 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/36.0.839.0 Safari/534.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_7) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/14.0.880.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/22.0.864.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/17.0.850.0 Safari/532.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/23.0.824.0 Safari/537.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4 rv:6.0; CU) AppleWebKit/533.0.1 (KHTML, like Gecko) Version/5.1.7 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/17.0.855.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/14.0.898.0 Safari/532.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.9.9; rv:15.6) Gecko/20100101 Firefox/15.6.6
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/34.0.870.0 Safari/535.1.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:14.7) Gecko/20100101 Firefox/14.7.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/39.0.871.0 Safari/533.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_7 rv:6.0; FY) AppleWebKit/532.0.2 (KHTML, like Gecko) Version/4.1.5 Safari/532.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/28.0.826.0 Safari/532.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/16.0.846.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/34.0.820.0 Safari/532.1.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/3.1; .NET CLR 1.6.40481.8)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/24.0.868.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/34.0.863.0 Safari/538.2.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_6 rv:3.0; AF) AppleWebKit/534.2.2 (KHTML, like Gecko) Version/7.1.8 Safari/534.2.2
Opera/13.14 (Windows NT 5.1; U; FY Presto/2.9.181 Version/12.00)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/25.0.876.0 Safari/535.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/6.0; .NET CLR 1.4.83437.5)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6.8; rv:6.9) Gecko/20100101 Firefox/6.9.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6.0; rv:7.1) Gecko/20100101 Firefox/7.1.7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/14.0.891.0 Safari/533.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/37.0.897.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/23.0.877.0 Safari/535.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:4.0; FR) AppleWebKit/537.2.0 (KHTML, like Gecko) Version/4.0.9 Safari/537.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.1.2 (KHTML, like Gecko) Chrome/18.0.880.0 Safari/536.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.1.2 (KHTML, like Gecko) Chrome/38.0.827.0 Safari/535.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/37.0.897.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/31.0.804.0 Safari/538.1.0
Opera/13.54 (Windows NT 5.2; U; VI Presto/2.9.174 Version/11.00)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/29.0.820.0 Safari/537.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/5.0; .NET CLR 2.8.84696.1)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/33.0.808.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/29.0.818.0 Safari/532.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10.4; rv:9.2) Gecko/20100101 Firefox/9.2.4
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/34.0.865.0 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/29.0.840.0 Safari/536.0.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/6.0; .NET CLR 3.5.20305.7)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8 rv:5.0; CA) AppleWebKit/535.0.0 (KHTML, like Gecko) Version/7.1.1 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/30.0.883.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/37.0.836.0 Safari/536.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5 rv:5.0; KA) AppleWebKit/537.2.2 (KHTML, like Gecko) Version/4.1.1 Safari/537.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_0) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/19.0.846.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/20.0.832.0 Safari/531.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/24.0.804.0 Safari/538.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/27.0.802.0 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/25.0.811.0 Safari/533.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/7.0; .NET CLR 2.3.10274.3)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/37.0.807.0 Safari/532.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/23.0.807.0 Safari/531.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4 rv:6.0; FJ) AppleWebKit/532.0.1 (KHTML, like Gecko) Version/7.1.7 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/31.0.870.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/32.0.881.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/28.0.837.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/20.0.841.0 Safari/531.1.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/4.0; .NET CLR 4.0.59005.1)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.1.2 (KHTML, like Gecko) Chrome/19.0.856.0 Safari/538.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/34.0.834.0 Safari/533.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/17.0.806.0 Safari/534.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_6) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/24.0.893.0 Safari/531.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_8 rv:4.0; BO) AppleWebKit/531.2.2 (KHTML, like Gecko) Version/6.1.10 Safari/531.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_2 rv:3.0; SK) AppleWebKit/534.1.2 (KHTML, like Gecko) Version/4.0.2 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/23.0.804.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/27.0.849.0 Safari/534.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_8 rv:4.0; OC) AppleWebKit/537.0.2 (KHTML, like Gecko) Version/7.1.6 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/39.0.825.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/35.0.816.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.1.2 (KHTML, like Gecko) Chrome/29.0.860.0 Safari/536.1.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/5.1; .NET CLR 4.5.54793.7)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/35.0.808.0 Safari/534.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5.5; rv:9.7) Gecko/20100101 Firefox/9.7.8
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0.4
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10.7; rv:10.7) Gecko/20100101 Firefox/10.7.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/27.0.896.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/22.0.870.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/33.0.806.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.2.0 (KHTML, like Gecko) Chrome/22.0.846.0 Safari/535.2.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/3.0; .NET CLR 2.4.94327.5)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3 rv:3.0; UR) AppleWebKit/535.2.1 (KHTML, like Gecko) Version/4.1.10 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/39.0.835.0 Safari/534.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/39.0.878.0 Safari/532.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/23.0.829.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/16.0.804.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/27.0.862.0 Safari/531.2.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/22.0.820.0 Safari/537.2.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Trident/5.0; .NET CLR 2.4.75254.1)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/33.0.812.0 Safari/533.0.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/4.1; .NET CLR 1.9.13974.8)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/17.0.828.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/38.0.834.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/26.0.884.0 Safari/532.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_9 rv:5.0; NL) AppleWebKit/534.0.1 (KHTML, like Gecko) Version/5.1.10 Safari/534.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.2; Trident/4.1; .NET CLR 1.8.67363.2)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/28.0.896.0 Safari/534.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/39.0.828.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/35.0.846.0 Safari/537.1.0
Opera/12.63 (Windows NT 6.0; U; LT Presto/2.9.190 Version/12.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5.6; rv:9.3) Gecko/20100101 Firefox/9.3.5
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/33.0.852.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/25.0.890.0 Safari/538.1.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/3.1; .NET CLR 4.3.24346.6)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/36.0.814.0 Safari/538.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_3 rv:2.0; MK) AppleWebKit/535.0.0 (KHTML, like Gecko) Version/7.0.6 Safari/535.0.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.3; Trident/6.1; .NET CLR 3.9.29644.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/29.0.861.0 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/31.0.858.0 Safari/532.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/14.0.863.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/34.0.865.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/25.0.860.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/27.0.838.0 Safari/532.2.0
Opera/10.33 (Windows NT 5.1; U; FR Presto/2.9.179 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/19.0.849.0 Safari/535.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/37.0.896.0 Safari/531.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/18.0.859.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/17.0.801.0 Safari/534.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/26.0.810.0 Safari/537.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.35768.8)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/31.0.863.0 Safari/532.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_1 rv:6.0; HI) AppleWebKit/533.1.2 (KHTML, like Gecko) Version/7.0.2 Safari/533.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10.9; rv:5.7) Gecko/20100101 Firefox/5.7.8
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/22.0.857.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/16.0.858.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/39.0.878.0 Safari/533.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8 rv:3.0; TY) AppleWebKit/536.2.0 (KHTML, like Gecko) Version/6.1.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/27.0.892.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/532.0.1 (KHTML, like Gecko) Chrome/37.0.875.0 Safari/532.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/5.0; .NET CLR 2.7.60602.1)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/25.0.891.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/23.0.812.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/30.0.877.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/31.0.885.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/31.0.865.0 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/26.0.880.0 Safari/537.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/5.0; .NET CLR 3.7.22414.9)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/35.0.842.0 Safari/531.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.0; Trident/6.1; .NET CLR 4.8.26312.4)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.3; Trident/6.1; .NET CLR 1.8.16851.3)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/35.0.873.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/25.0.807.0 Safari/536.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9.3; rv:9.8) Gecko/20100101 Firefox/9.8.7
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/31.0.832.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/37.0.882.0 Safari/534.0.0
Mozilla/5.0 (Windows NT 5.0; WOW64; rv:15.2) Gecko/20100101 Firefox/15.2.1
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_7 rv:5.0; HE) AppleWebKit/532.2.0 (KHTML, like Gecko) Version/7.0.2 Safari/532.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/24.0.839.0 Safari/538.2.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.1; .NET CLR 4.2.51723.1)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.0.2 (KHTML, like Gecko) Chrome/18.0.867.0 Safari/531.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/31.0.855.0 Safari/534.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_7) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/31.0.853.0 Safari/535.1.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.2; Trident/5.1; .NET CLR 2.8.67944.1)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/17.0.836.0 Safari/538.1.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/4.0; .NET CLR 3.1.64544.3)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/29.0.888.0 Safari/532.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6.7; rv:8.3) Gecko/20100101 Firefox/8.3.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/21.0.827.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/22.0.877.0 Safari/535.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4 rv:5.0; AR) AppleWebKit/535.2.1 (KHTML, like Gecko) Version/7.1.4 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/19.0.809.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/536.0.2 (KHTML, like Gecko) Chrome/33.0.845.0 Safari/536.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7 rv:5.0; FY) AppleWebKit/536.1.1 (KHTML, like Gecko) Version/4.0.4 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/17.0.888.0 Safari/533.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/21.0.821.0 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/14.0.891.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/25.0.811.0 Safari/531.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_5 rv:4.0; CU) AppleWebKit/537.2.2 (KHTML, like Gecko) Version/5.1.1 Safari/537.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/14.0.854.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/13.0.857.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/35.0.874.0 Safari/534.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3 rv:6.0; CU) AppleWebKit/531.0.0 (KHTML, like Gecko) Version/4.1.4 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/31.0.869.0 Safari/534.1.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Trident/7.1; .NET CLR 1.4.43776.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/21.0.817.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/31.0.862.0 Safari/534.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/33.0.862.0 Safari/533.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/22.0.868.0 Safari/531.2.2
Mozilla/5.0 (Windows NT 5.0; rv:9.6) Gecko/20100101 Firefox/9.6.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/7.0; .NET CLR 2.4.56835.0)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/35.0.881.0 Safari/534.2.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/6.0; .NET CLR 2.4.44989.4)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/39.0.894.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/13.0.868.0 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/34.0.832.0 Safari/538.2.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.0; Trident/5.0; .NET CLR 4.3.61243.8)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/17.0.876.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/32.0.811.0 Safari/537.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/19.0.880.0 Safari/531.2.2
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:15.2) Gecko/20100101 Firefox/15.2.7
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_9 rv:3.0; BE) AppleWebKit/537.1.2 (KHTML, like Gecko) Version/4.0.10 Safari/537.1.2
Opera/11.82 (Windows NT 6.0; U; NL Presto/2.9.184 Version/12.00)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/33.0.841.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/26.0.855.0 Safari/536.1.1
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:9.8) Gecko/20100101 Firefox/9.8.3
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/37.0.883.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/536.2.1 (KHTML, like Gecko) Chrome/38.0.807.0 Safari/536.2.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/4.1; .NET CLR 1.5.71921.5)
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.3; Trident/5.1; .NET CLR 1.9.71865.1)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/17.0.828.0 Safari/538.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/14.0.817.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/28.0.876.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/28.0.815.0 Safari/533.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/28.0.876.0 Safari/535.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_9 rv:2.0; AN) AppleWebKit/531.0.2 (KHTML, like Gecko) Version/7.1.10 Safari/531.0.2
Opera/14.33 (Windows NT 5.2; U; CU Presto/2.9.168 Version/11.00)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/24.0.835.0 Safari/538.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/22.0.862.0 Safari/535.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_5 rv:6.0; EO) AppleWebKit/535.2.2 (KHTML, like Gecko) Version/5.1.7 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/33.0.872.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/24.0.847.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/24.0.834.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/29.0.883.0 Safari/537.2.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/6.1; .NET CLR 3.7.84044.8)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.0.2 (KHTML, like Gecko) Chrome/32.0.841.0 Safari/531.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/19.0.839.0 Safari/535.2.1
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:10.1) Gecko/20100101 Firefox/10.1.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.3; Trident/6.1; .NET CLR 2.6.45189.2)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_8 rv:3.0; HU) AppleWebKit/535.0.2 (KHTML, like Gecko) Version/7.0.4 Safari/535.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_1) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/37.0.861.0 Safari/532.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.7.7; rv:5.5) Gecko/20100101 Firefox/5.5.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/3.1; .NET CLR 1.5.49411.1)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Trident/7.1; .NET CLR 2.9.80709.4)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_2 rv:3.0; VI) AppleWebKit/531.2.2 (KHTML, like Gecko) Version/4.1.8 Safari/531.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6.8; rv:13.2) Gecko/20100101 Firefox/13.2.9
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/5.0; .NET CLR 4.5.23243.3)
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/6.0; .NET CLR 1.9.25307.4)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/26.0.843.0 Safari/536.1.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/3.0; .NET CLR 1.5.57280.2)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/31.0.862.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/26.0.878.0 Safari/533.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/23.0.879.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/24.0.835.0 Safari/537.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/21.0.830.0 Safari/533.1.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/7.1; .NET CLR 4.2.66410.4)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_7 rv:6.0; ID) AppleWebKit/532.2.1 (KHTML, like Gecko) Version/7.0.0 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/39.0.881.0 Safari/537.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10.1; rv:9.2) Gecko/20100101 Firefox/9.2.3
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/19.0.801.0 Safari/535.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/21.0.866.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/30.0.866.0 Safari/531.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/26.0.822.0 Safari/538.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/21.0.812.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.2.2 (KHTML, like Gecko) Chrome/17.0.862.0 Safari/532.2.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/4.0; .NET CLR 3.2.37629.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/13.0.860.0 Safari/538.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/20.0.856.0 Safari/537.2.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/3.0; .NET CLR 1.5.66242.4)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/34.0.809.0 Safari/533.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_9 rv:3.0; SQ) AppleWebKit/531.0.0 (KHTML, like Gecko) Version/6.1.4 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/31.0.847.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/15.0.869.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/19.0.806.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/532.2.1 (KHTML, like Gecko) Chrome/30.0.881.0 Safari/532.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_9 rv:6.0; SR) AppleWebKit/532.0.2 (KHTML, like Gecko) Version/7.0.1 Safari/532.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/33.0.836.0 Safari/538.2.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/3.0; .NET CLR 3.9.77367.4)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.1 (KHTML, like Gecko) Chrome/17.0.882.0 Safari/536.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/30.0.873.0 Safari/535.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_6 rv:5.0; FI) AppleWebKit/535.2.2 (KHTML, like Gecko) Version/6.1.6 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/20.0.886.0 Safari/531.0.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/6.1; .NET CLR 2.9.22429.5)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/29.0.838.0 Safari/538.0.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/5.1; .NET CLR 3.3.45840.7)
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/6.0; .NET CLR 4.1.72145.0)
Opera/14.83 (Windows NT 5.2; U; SQ Presto/2.9.162 Version/12.00)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.0; Trident/6.1; .NET CLR 1.8.12838.1)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/39.0.854.0 Safari/531.2.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/4.0; .NET CLR 3.9.28343.3)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/26.0.841.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/37.0.873.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/19.0.821.0 Safari/531.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/37.0.870.0 Safari/531.1.1
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:8.5) Gecko/20100101 Firefox/8.5.3
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/38.0.834.0 Safari/536.2.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/3.1; .NET CLR 3.5.59079.5)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/29.0.878.0 Safari/531.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/16.0.850.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/34.0.857.0 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/37.0.836.0 Safari/531.2.0
Mozilla/5.0 (Macintosh; PPC Mac OS X 10.6.8; rv:10.0) Gecko/20100101 Firefox/10.0.3
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_2 rv:2.0; MY) AppleWebKit/537.1.1 (KHTML, like Gecko) Version/4.1.9 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/29.0.878.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/26.0.871.0 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/20.0.821.0 Safari/536.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_0) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/23.0.843.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/13.0.831.0 Safari/531.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/36.0.841.0 Safari/532.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_9) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/21.0.803.0 Safari/531.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/29.0.811.0 Safari/537.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 rv:2.0; RM) AppleWebKit/538.1.1 (KHTML, like Gecko) Version/5.0.7 Safari/538.1.1
Opera/9.59 (Macintosh; Intel Mac OS X 10.9.6 U; AN Presto/2.9.178 Version/11.00)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/17.0.855.0 Safari/537.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/23.0.816.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/37.0.869.0 Safari/532.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/39.0.892.0 Safari/531.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/33.0.863.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/36.0.859.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/38.0.878.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/27.0.876.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/22.0.897.0 Safari/536.2.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/4.0; .NET CLR 4.4.66508.4)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_0) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/39.0.859.0 Safari/534.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/23.0.886.0 Safari/531.1.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.1; .NET CLR 2.3.68400.1)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/39.0.856.0 Safari/535.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/3.0; .NET CLR 1.1.58394.7)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/15.0.834.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.1.2 (KHTML, like Gecko) Chrome/33.0.863.0 Safari/535.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/20.0.842.0 Safari/531.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/35.0.858.0 Safari/537.0.1
Mozilla/5.0 (Windows NT 5.0; WOW64; rv:15.2) Gecko/20100101 Firefox/15.2.5
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/6.0; .NET CLR 4.4.30004.3)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/19.0.840.0 Safari/534.2.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/3.0; .NET CLR 4.7.85971.9)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/16.0.889.0 Safari/532.1.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/6.1; .NET CLR 4.5.57686.1)
Opera/9.19 (Windows NT 6.0; U; SO Presto/2.9.183 Version/11.00)
Opera/10.47 (Windows NT 6.0; U; BG Presto/2.9.161 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/14.0.835.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/25.0.895.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/17.0.816.0 Safari/534.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5.1; rv:14.3) Gecko/20100101 Firefox/14.3.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/29.0.862.0 Safari/531.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3 rv:4.0; JA) AppleWebKit/535.0.1 (KHTML, like Gecko) Version/5.1.0 Safari/535.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; .NET CLR 2.5.10585.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/13.0.843.0 Safari/534.1.1
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.9.0; rv:12.3) Gecko/20100101 Firefox/12.3.8
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/25.0.897.0 Safari/535.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/20.0.891.0 Safari/532.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_3) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/37.0.814.0 Safari/534.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/5.0; .NET CLR 4.4.58415.8)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/24.0.890.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/32.0.886.0 Safari/535.1.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.0; Trident/7.0; .NET CLR 3.3.44577.0)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/35.0.840.0 Safari/538.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/7.1; .NET CLR 1.4.38059.1)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/31.0.875.0 Safari/531.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/37.0.893.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.2.0 (KHTML, like Gecko) Chrome/14.0.802.0 Safari/535.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/16.0.874.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/13.0.800.0 Safari/533.2.1
Mozilla/5.0 (Windows NT 6.1; rv:11.0) Gecko/20100101 Firefox/11.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/13.0.826.0 Safari/534.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.1; .NET CLR 3.8.83092.5)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/31.0.821.0 Safari/535.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_5 rv:3.0; KO) AppleWebKit/538.0.2 (KHTML, like Gecko) Version/7.1.4 Safari/538.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9.2; rv:14.9) Gecko/20100101 Firefox/14.9.6
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/17.0.856.0 Safari/535.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/4.0; .NET CLR 2.1.72169.8)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/35.0.804.0 Safari/533.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/37.0.862.0 Safari/533.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_9 rv:5.0; BE) AppleWebKit/537.2.0 (KHTML, like Gecko) Version/6.1.5 Safari/537.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/19.0.888.0 Safari/532.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/34.0.869.0 Safari/538.2.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/6.1; .NET CLR 3.5.67726.3)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/31.0.861.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/18.0.813.0 Safari/535.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8.3; rv:14.8) Gecko/20100101 Firefox/14.8.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_7) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/14.0.824.0 Safari/531.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4 rv:4.0; GV) AppleWebKit/536.2.0 (KHTML, like Gecko) Version/6.0.8 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/33.0.876.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/29.0.892.0 Safari/532.2.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.0; .NET CLR 2.2.95580.7)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/22.0.821.0 Safari/534.2.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/7.0; .NET CLR 2.1.97330.2)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/28.0.839.0 Safari/538.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/36.0.886.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/28.0.833.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/29.0.887.0 Safari/535.2.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/4.1; .NET CLR 2.8.14084.3)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/33.0.823.0 Safari/533.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_7) AppleWebKit/536.0.2 (KHTML, like Gecko) Chrome/15.0.880.0 Safari/536.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/7.0; .NET CLR 2.8.99300.7)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/30.0.881.0 Safari/538.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7.5; rv:10.4) Gecko/20100101 Firefox/10.4.9
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/4.1; .NET CLR 1.8.13957.3)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.2.0 (KHTML, like Gecko) Chrome/19.0.880.0 Safari/537.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6.4; rv:6.7) Gecko/20100101 Firefox/6.7.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.7.4; rv:13.6) Gecko/20100101 Firefox/13.6.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/13.0.838.0 Safari/537.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1 rv:6.0; AS) AppleWebKit/532.2.2 (KHTML, like Gecko) Version/7.0.8 Safari/532.2.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/5.1; .NET CLR 2.3.27548.8)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.0; Trident/7.1; .NET CLR 3.3.60858.1)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/35.0.889.0 Safari/533.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/34.0.849.0 Safari/531.2.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_3) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/32.0.838.0 Safari/534.2.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/3.1; .NET CLR 1.2.75068.8)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/31.0.863.0 Safari/538.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_4 rv:5.0; HE) AppleWebKit/531.2.0 (KHTML, like Gecko) Version/5.1.8 Safari/531.2.0
Mozilla/5.0 (Windows NT 5.2; rv:9.2) Gecko/20100101 Firefox/9.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_1 rv:3.0; CU) AppleWebKit/535.0.2 (KHTML, like Gecko) Version/4.1.6 Safari/535.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_2 rv:5.0; FA) AppleWebKit/536.2.0 (KHTML, like Gecko) Version/6.0.3 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/29.0.858.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/13.0.867.0 Safari/535.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_9 rv:2.0; EO) AppleWebKit/533.0.2 (KHTML, like Gecko) Version/6.1.10 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/27.0.823.0 Safari/531.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_9 rv:2.0; VI) AppleWebKit/534.2.2 (KHTML, like Gecko) Version/4.1.1 Safari/534.2.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/7.0; .NET CLR 1.7.18278.8)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_4 rv:6.0; BR) AppleWebKit/537.2.1 (KHTML, like Gecko) Version/5.1.10 Safari/537.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/19.0.852.0 Safari/532.2.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4 rv:4.0; MT) AppleWebKit/533.2.2 (KHTML, like Gecko) Version/7.1.1 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/15.0.865.0 Safari/538.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_4 rv:3.0; MT) AppleWebKit/534.1.0 (KHTML, like Gecko) Version/4.1.1 Safari/534.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/20.0.874.0 Safari/538.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_5) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/25.0.823.0 Safari/535.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/15.0.802.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/25.0.853.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/28.0.876.0 Safari/537.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/24.0.854.0 Safari/535.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8 rv:3.0; SR) AppleWebKit/537.0.1 (KHTML, like Gecko) Version/4.0.8 Safari/537.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_8 rv:5.0; SC) AppleWebKit/534.2.2 (KHTML, like Gecko) Version/4.0.3 Safari/534.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/32.0.854.0 Safari/534.2.2
Mozilla/5.0 (Windows NT 5.1; Win64; x64; rv:11.1) Gecko/20100101 Firefox/11.1.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3 rv:2.0; MT) AppleWebKit/532.2.0 (KHTML, like Gecko) Version/5.0.10 Safari/532.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_4 rv:4.0; VI) AppleWebKit/535.1.1 (KHTML, like Gecko) Version/7.0.1 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/24.0.826.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/23.0.838.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/24.0.883.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/21.0.892.0 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.0)AppleWebKit/536.2.0 (KHTML, like Gecko) Version/4.0.9 Safari/536.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.9.1; rv:9.7) Gecko/20100101 Firefox/9.7.6
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/14.0.801.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/38.0.860.0 Safari/537.1.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.1; Trident/6.1; .NET CLR 3.7.93452.8)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/26.0.854.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/26.0.853.0 Safari/534.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_7) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/13.0.859.0 Safari/533.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/19.0.809.0 Safari/534.2.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_9 rv:2.0; UK) AppleWebKit/538.2.2 (KHTML, like Gecko) Version/5.0.5 Safari/538.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_1 rv:2.0; LI) AppleWebKit/531.2.0 (KHTML, like Gecko) Version/7.1.4 Safari/531.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/15.0.873.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/27.0.874.0 Safari/533.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/15.0.809.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/24.0.840.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.1.0 (KHTML, like Gecko) Chrome/38.0.800.0 Safari/536.1.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0; .NET CLR 3.8.77952.0)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/36.0.856.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/15.0.800.0 Safari/538.1.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5 rv:2.0; SQ) AppleWebKit/533.0.1 (KHTML, like Gecko) Version/5.1.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/36.0.865.0 Safari/532.2.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.4) Gecko/20100101 Firefox/11.4.7
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_7) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/20.0.874.0 Safari/534.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/24.0.885.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/28.0.887.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/36.0.831.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/34.0.886.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/22.0.834.0 Safari/533.1.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.3; Trident/3.1; .NET CLR 3.8.41441.8)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/24.0.827.0 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/20.0.803.0 Safari/533.2.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/6.1; .NET CLR 4.7.60171.0)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_4 rv:6.0; RO) AppleWebKit/533.0.2 (KHTML, like Gecko) Version/6.1.10 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/25.0.878.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/28.0.809.0 Safari/531.1.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.7.1; rv:7.9) Gecko/20100101 Firefox/7.9.0
Opera/14.78 (Windows NT 5.1; U; SW Presto/2.9.161 Version/11.00)
Mozilla/5.0 (Windows NT 5.2; WOW64; rv:11.4) Gecko/20100101 Firefox/11.4.5
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/23.0.827.0 Safari/537.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.3; Trident/4.1; .NET CLR 2.5.27673.8)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/35.0.845.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/38.0.876.0 Safari/538.2.0
Mozilla/5.0 (Windows NT 6.1; rv:9.1) Gecko/20100101 Firefox/9.1.3
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.7.4; rv:15.4) Gecko/20100101 Firefox/15.4.8
Opera/11.62 (Windows NT 5.1; U; EO Presto/2.9.163 Version/10.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.9.0; rv:14.0) Gecko/20100101 Firefox/14.0.7
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/39.0.862.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.1.2 (KHTML, like Gecko) Chrome/25.0.833.0 Safari/538.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/18.0.822.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/20.0.847.0 Safari/537.2.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.0; .NET CLR 1.0.30642.4)
Opera/11.81 (Windows NT 5.3; U; AN Presto/2.9.175 Version/12.00)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_8 rv:5.0; HI) AppleWebKit/532.2.2 (KHTML, like Gecko) Version/4.1.1 Safari/532.2.2
Opera/9.87 (Windows NT 6.1; U; LB Presto/2.9.167 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/14.0.809.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/15.0.805.0 Safari/534.1.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/7.1; .NET CLR 3.4.18789.6)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/27.0.859.0 Safari/537.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/23.0.845.0 Safari/536.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.2; Trident/3.0; .NET CLR 1.2.34566.4)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_9 rv:4.0; FO) AppleWebKit/537.0.1 (KHTML, like Gecko) Version/7.0.10 Safari/537.0.1
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/5.1; .NET CLR 1.2.68642.2)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/39.0.898.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/29.0.858.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/19.0.898.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/15.0.882.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/26.0.872.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/37.0.896.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/27.0.824.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/38.0.894.0 Safari/531.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9.1; rv:14.4) Gecko/20100101 Firefox/14.4.4
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/15.0.829.0 Safari/535.0.2
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.7.6; rv:6.0) Gecko/20100101 Firefox/6.0.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/5.1; .NET CLR 3.9.91048.7)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/35.0.856.0 Safari/538.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/7.1; .NET CLR 2.6.80712.9)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/14.0.809.0 Safari/537.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/19.0.841.0 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/37.0.877.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/35.0.898.0 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/33.0.821.0 Safari/533.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/536.1.2 (KHTML, like Gecko) Chrome/27.0.841.0 Safari/536.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_9 rv:4.0; KA) AppleWebKit/536.2.1 (KHTML, like Gecko) Version/4.0.3 Safari/536.2.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_6 rv:4.0; ID) AppleWebKit/533.2.2 (KHTML, like Gecko) Version/6.1.8 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/30.0.899.0 Safari/533.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_2 rv:2.0; ET) AppleWebKit/534.0.0 (KHTML, like Gecko) Version/6.0.6 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/36.0.812.0 Safari/534.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/7.1; .NET CLR 1.5.12446.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/5.1; .NET CLR 4.4.49991.4)
Opera/12.93 (Windows NT 6.0; U; CY Presto/2.9.172 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/38.0.897.0 Safari/531.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/34.0.897.0 Safari/533.0.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/5.1; .NET CLR 1.3.41528.6)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/38.0.878.0 Safari/533.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/3.1; .NET CLR 4.8.31382.1)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/39.0.863.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/14.0.804.0 Safari/534.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/30.0.885.0 Safari/531.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/23.0.812.0 Safari/538.2.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_4 rv:2.0; DE) AppleWebKit/536.0.0 (KHTML, like Gecko) Version/7.0.3 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/31.0.862.0 Safari/532.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/16.0.899.0 Safari/538.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/14.0.859.0 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/27.0.894.0 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/33.0.808.0 Safari/538.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_5) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/36.0.826.0 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/30.0.896.0 Safari/535.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/20.0.852.0 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/25.0.895.0 Safari/531.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_1 rv:6.0; LA) AppleWebKit/535.0.0 (KHTML, like Gecko) Version/5.1.7 Safari/535.0.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/7.0; .NET CLR 4.6.30847.7)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_3 rv:2.0; VI) AppleWebKit/531.0.2 (KHTML, like Gecko) Version/7.0.0 Safari/531.0.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/5.0; .NET CLR 4.6.16893.0)
Mozilla/5.0 (X11; Linux x86_64; rv:10.3) Gecko/20100101 Firefox/10.3.7
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/22.0.820.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.1.0 (KHTML, like Gecko) Chrome/31.0.885.0 Safari/533.1.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/5.0; .NET CLR 3.4.37258.7)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/35.0.857.0 Safari/533.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10.5; rv:12.0) Gecko/20100101 Firefox/12.0.4
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/26.0.826.0 Safari/532.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10.1; rv:13.4) Gecko/20100101 Firefox/13.4.8
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/21.0.877.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/17.0.815.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/35.0.877.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/28.0.837.0 Safari/533.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/25.0.811.0 Safari/537.1.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/5.0; .NET CLR 4.5.16173.4)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.0.2 (KHTML, like Gecko) Chrome/35.0.874.0 Safari/536.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/533.1.2 (KHTML, like Gecko) Chrome/19.0.898.0 Safari/533.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/18.0.876.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/536.0.0 (KHTML, like Gecko) Chrome/22.0.853.0 Safari/536.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.2.0 (KHTML, like Gecko) Chrome/15.0.845.0 Safari/537.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.0 (KHTML, like Gecko) Chrome/15.0.821.0 Safari/531.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/31.0.833.0 Safari/534.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3) AppleWebKit/534.2.2 (KHTML, like Gecko) Chrome/29.0.860.0 Safari/534.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/14.0.845.0 Safari/534.0.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/4.0; .NET CLR 1.0.52321.2)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/27.0.898.0 Safari/535.0.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/7.1; .NET CLR 3.9.60848.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/25.0.863.0 Safari/535.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_7) AppleWebKit/537.0.0 (KHTML, like Gecko) Chrome/13.0.812.0 Safari/537.0.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.8.0; rv:13.0) Gecko/20100101 Firefox/13.0.4
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/5.1; .NET CLR 1.7.75372.1)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/22.0.861.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/20.0.874.0 Safari/534.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/14.0.818.0 Safari/537.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/39.0.804.0 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/34.0.829.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.0.1 (KHTML, like Gecko) Chrome/24.0.835.0 Safari/536.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/35.0.832.0 Safari/537.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 rv:2.0; AB) AppleWebKit/531.1.2 (KHTML, like Gecko) Version/6.0.5 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/13.0.816.0 Safari/538.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/35.0.893.0 Safari/538.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_5) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/22.0.834.0 Safari/533.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_0 rv:4.0; FY) AppleWebKit/532.2.1 (KHTML, like Gecko) Version/7.0.10 Safari/532.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/28.0.887.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/36.0.858.0 Safari/533.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/33.0.850.0 Safari/538.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/39.0.811.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/34.0.865.0 Safari/537.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_2 rv:2.0; KY) AppleWebKit/536.2.1 (KHTML, like Gecko) Version/6.1.8 Safari/536.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/14.0.862.0 Safari/537.2.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; .NET CLR 1.7.67835.8)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.0.1 (KHTML, like Gecko) Chrome/30.0.899.0 Safari/533.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/34.0.804.0 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/25.0.889.0 Safari/537.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/30.0.884.0 Safari/538.2.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.2; Trident/4.0; .NET CLR 4.9.91219.7)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5.2; rv:5.8) Gecko/20100101 Firefox/5.8.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/34.0.891.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.0.0 (KHTML, like Gecko) Chrome/13.0.885.0 Safari/532.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/28.0.830.0 Safari/537.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/28.0.891.0 Safari/534.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_5 rv:5.0; VI) AppleWebKit/538.0.1 (KHTML, like Gecko) Version/7.0.2 Safari/538.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.3; Trident/5.0; .NET CLR 1.9.19888.5)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/20.0.802.0 Safari/534.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/18.0.890.0 Safari/535.0.1
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/4.1; .NET CLR 4.9.79808.0)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/532.1.0 (KHTML, like Gecko) Chrome/22.0.810.0 Safari/532.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.1 (KHTML, like Gecko) Chrome/16.0.887.0 Safari/535.0.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_9 rv:5.0; AZ) AppleWebKit/535.0.0 (KHTML, like Gecko) Version/4.0.9 Safari/535.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4 rv:5.0; SO) AppleWebKit/537.1.1 (KHTML, like Gecko) Version/6.0.2 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/35.0.895.0 Safari/533.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/21.0.807.0 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/24.0.803.0 Safari/537.0.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/3.0; .NET CLR 1.4.80991.8)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/27.0.851.0 Safari/536.2.0
Opera/9.21 (Windows NT 6.0; U; FA Presto/2.9.177 Version/10.00)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/15.0.814.0 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/29.0.888.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/14.0.868.0 Safari/533.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.0.0 (KHTML, like Gecko) Chrome/13.0.881.0 Safari/538.0.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.3; Trident/6.0; .NET CLR 2.0.55257.8)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/32.0.892.0 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/31.0.868.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/25.0.869.0 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/16.0.816.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.2.2 (KHTML, like Gecko) Chrome/31.0.863.0 Safari/533.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.1.2 (KHTML, like Gecko) Chrome/29.0.875.0 Safari/535.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/17.0.893.0 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/30.0.899.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.2.2 (KHTML, like Gecko) Chrome/31.0.881.0 Safari/532.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.2 (KHTML, like Gecko) Chrome/25.0.893.0 Safari/534.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/17.0.858.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/14.0.863.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/532.2.2 (KHTML, like Gecko) Chrome/29.0.830.0 Safari/532.2.2
Mozilla/5.0 (Windows NT 6.2; rv:11.8) Gecko/20100101 Firefox/11.8.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/31.0.828.0 Safari/537.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/31.0.891.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/28.0.864.0 Safari/537.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1 rv:6.0; SV) AppleWebKit/532.1.2 (KHTML, like Gecko) Version/6.0.8 Safari/532.1.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.7.8; rv:11.9) Gecko/20100101 Firefox/11.9.7
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/33.0.829.0 Safari/537.1.1
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_3) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/22.0.853.0 Safari/537.1.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/4.0; .NET CLR 2.6.87899.4)
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_2 rv:4.0; MS) AppleWebKit/536.1.0 (KHTML, like Gecko) Version/7.0.6 Safari/536.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/37.0.830.0 Safari/532.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_1 rv:3.0; FA) AppleWebKit/536.1.2 (KHTML, like Gecko) Version/5.0.3 Safari/536.1.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/6.1; .NET CLR 3.7.66604.2)
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_9_0 rv:6.0; HU) AppleWebKit/538.0.2 (KHTML, like Gecko) Version/7.1.6 Safari/538.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/31.0.852.0 Safari/532.1.2
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_6 rv:6.0; CU) AppleWebKit/538.0.1 (KHTML, like Gecko) Version/5.1.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.1.0 (KHTML, like Gecko) Chrome/38.0.845.0 Safari/531.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/29.0.821.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/31.0.895.0 Safari/535.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.1.1 (KHTML, like Gecko) Chrome/15.0.888.0 Safari/536.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/30.0.862.0 Safari/534.1.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.0; Trident/7.0; .NET CLR 2.0.97735.7)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9.2; rv:6.2) Gecko/20100101 Firefox/6.2.9
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/39.0.807.0 Safari/536.2.0
Mozilla/5.0 (Windows NT 6.1; rv:11.3) Gecko/20100101 Firefox/11.3.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/16.0.802.0 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/33.0.820.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.1.0 (KHTML, like Gecko) Chrome/16.0.862.0 Safari/536.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/37.0.883.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/21.0.898.0 Safari/533.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/27.0.847.0 Safari/537.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/20.0.815.0 Safari/537.1.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/7.0; .NET CLR 2.9.16132.6)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/14.0.884.0 Safari/538.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/14.0.845.0 Safari/531.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.0.2 (KHTML, like Gecko) Chrome/14.0.889.0 Safari/536.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_3 rv:3.0; MY) AppleWebKit/533.2.0 (KHTML, like Gecko) Version/7.0.10 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/25.0.871.0 Safari/531.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/36.0.827.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/30.0.839.0 Safari/538.2.1
Opera/10.87 (Windows NT 5.0; U; CO Presto/2.9.162 Version/12.00)
Mozilla/5.0 (Windows NT 5.2; WOW64; rv:12.9) Gecko/20100101 Firefox/12.9.3
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/5.0; .NET CLR 3.7.64000.0)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.2; Trident/3.0; .NET CLR 3.6.37284.9)
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/28.0.853.0 Safari/537.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/532.0.2 (KHTML, like Gecko) Chrome/13.0.878.0 Safari/532.0.2
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_1 rv:5.0; JA) AppleWebKit/538.1.0 (KHTML, like Gecko) Version/4.0.5 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.1.2 (KHTML, like Gecko) Chrome/29.0.837.0 Safari/535.1.2
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.3; Trident/5.0; .NET CLR 4.2.32639.0)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/537.2.1 (KHTML, like Gecko) Chrome/13.0.836.0 Safari/537.2.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/7.0; .NET CLR 4.8.19358.6)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.2.0 (KHTML, like Gecko) Chrome/34.0.867.0 Safari/537.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/535.2.2 (KHTML, like Gecko) Chrome/29.0.847.0 Safari/535.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/24.0.820.0 Safari/533.0.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2 rv:4.0; MO) AppleWebKit/538.0.0 (KHTML, like Gecko) Version/4.0.3 Safari/538.0.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_6 rv:5.0; SQ) AppleWebKit/531.0.1 (KHTML, like Gecko) Version/7.0.5 Safari/531.0.1
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/34.0.874.0 Safari/534.0.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/22.0.867.0 Safari/534.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/3.0; .NET CLR 4.0.76434.4)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.0.0 (KHTML, like Gecko) Chrome/17.0.818.0 Safari/531.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/32.0.871.0 Safari/533.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/32.0.854.0 Safari/535.0.0
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.1 (KHTML, like Gecko) Chrome/34.0.882.0 Safari/537.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.2.2 (KHTML, like Gecko) Chrome/26.0.830.0 Safari/536.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.0.2 (KHTML, like Gecko) Chrome/16.0.856.0 Safari/533.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/18.0.856.0 Safari/537.2.2
Opera/14.5 (Windows NT 6.0; U; CS Presto/2.9.170 Version/12.00)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/30.0.876.0 Safari/537.0.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/5.0; .NET CLR 3.1.76820.4)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.2.1 (KHTML, like Gecko) Chrome/17.0.851.0 Safari/536.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_7 rv:2.0; JA) AppleWebKit/538.1.1 (KHTML, like Gecko) Version/7.1.7 Safari/538.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/532.2.0 (KHTML, like Gecko) Chrome/35.0.804.0 Safari/532.2.0
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_4 rv:2.0; NB) AppleWebKit/538.0.1 (KHTML, like Gecko) Version/5.1.0 Safari/538.0.1
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/3.1; .NET CLR 1.4.82578.1)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/19.0.861.0 Safari/537.1.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/7.1; .NET CLR 3.3.81479.5)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/536.1.2 (KHTML, like Gecko) Chrome/18.0.813.0 Safari/536.1.2
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/4.1; .NET CLR 4.1.24046.7)
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/538.0.1 (KHTML, like Gecko) Chrome/28.0.850.0 Safari/538.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5.6; rv:9.8) Gecko/20100101 Firefox/9.8.9
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/535.1.0 (KHTML, like Gecko) Chrome/27.0.883.0 Safari/535.1.0
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/13.0.867.0 Safari/534.1.1
Opera/13.17 (Windows NT 5.0; U; CA Presto/2.9.177 Version/10.00)
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/5.1; .NET CLR 4.3.12356.5)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.1 (KHTML, like Gecko) Chrome/38.0.801.0 Safari/532.1.1
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_9 rv:6.0; MY) AppleWebKit/531.1.2 (KHTML, like Gecko) Version/5.1.0 Safari/531.1.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8.8; rv:10.1) Gecko/20100101 Firefox/10.1.6
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.0; Trident/7.0; .NET CLR 1.8.85802.0)
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/15.0.831.0 Safari/538.1.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.5.0; rv:10.5) Gecko/20100101 Firefox/10.5.8
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_7) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/16.0.887.0 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/38.0.834.0 Safari/538.1.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.0.1 (KHTML, like Gecko) Chrome/13.0.860.0 Safari/531.0.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/6.0; .NET CLR 4.7.30173.2)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_8 rv:5.0; MY) AppleWebKit/534.0.1 (KHTML, like Gecko) Version/5.0.0 Safari/534.0.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/31.0.834.0 Safari/537.0.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.1.0 (KHTML, like Gecko) Chrome/37.0.851.0 Safari/538.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/27.0.819.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/537.2.2 (KHTML, like Gecko) Chrome/17.0.861.0 Safari/537.2.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/29.0.841.0 Safari/531.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/531.2.2 (KHTML, like Gecko) Chrome/35.0.843.0 Safari/531.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.2.2 (KHTML, like Gecko) Chrome/18.0.835.0 Safari/538.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/20.0.856.0 Safari/533.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/26.0.801.0 Safari/538.2.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/3.0; .NET CLR 2.5.69435.1)
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/534.0.1 (KHTML, like Gecko) Chrome/29.0.851.0 Safari/534.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/538.2.1 (KHTML, like Gecko) Chrome/17.0.805.0 Safari/538.2.1
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/5.1; .NET CLR 4.2.90450.2)
Opera/14.98 (Windows NT 6.1; U; CO Presto/2.9.167 Version/12.00)
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/25.0.825.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.3) AppleWebKit/534.1.2 (KHTML, like Gecko) Chrome/39.0.846.0 Safari/534.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/35.0.838.0 Safari/538.2.0
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/14.0.891.0 Safari/535.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/532.1.2 (KHTML, like Gecko) Chrome/29.0.875.0 Safari/532.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.3) AppleWebKit/535.0.0 (KHTML, like Gecko) Chrome/21.0.895.0 Safari/535.0.0
Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/6.1; .NET CLR 3.7.25725.1)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/26.0.886.0 Safari/534.2.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 rv:2.0; EN) AppleWebKit/537.1.0 (KHTML, like Gecko) Version/7.1.0 Safari/537.1.0
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.3; Trident/6.1; .NET CLR 3.9.60807.7)
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/533.2.0 (KHTML, like Gecko) Chrome/34.0.876.0 Safari/533.2.0
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.3; Trident/4.1; .NET CLR 3.1.99967.9)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/15.0.865.0 Safari/537.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/534.1.0 (KHTML, like Gecko) Chrome/37.0.846.0 Safari/534.1.0
Mozilla/5.0 (Windows; U; Windows NT 5.2) AppleWebKit/531.0.2 (KHTML, like Gecko) Chrome/37.0.815.0 Safari/531.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/533.2.1 (KHTML, like Gecko) Chrome/23.0.894.0 Safari/533.2.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0 rv:4.0; DA) AppleWebKit/537.2.2 (KHTML, like Gecko) Version/6.1.1 Safari/537.2.2
Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/533.0.0 (KHTML, like Gecko) Chrome/34.0.815.0 Safari/533.0.0
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/7.1; .NET CLR 2.4.67678.8)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/534.2.1 (KHTML, like Gecko) Chrome/22.0.881.0 Safari/534.2.1
Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/32.0.873.0 Safari/531.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/31.0.828.0 Safari/537.0.2
Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.0; Trident/3.1; .NET CLR 2.7.68703.6)
Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/535.0.2 (KHTML, like Gecko) Chrome/17.0.858.0 Safari/535.0.2
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.3; Trident/5.0; .NET CLR 2.2.15091.1)
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/531.1.2 (KHTML, like Gecko) Chrome/33.0.893.0 Safari/531.1.2
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/30.0.852.0 Safari/531.2.1
Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/536.2.0 (KHTML, like Gecko) Chrome/19.0.891.0 Safari/536.2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1) AppleWebKit/538.2.0 (KHTML, like Gecko) Chrome/20.0.852.0 Safari/538.2.0